[default]
address = "0.0.0.0"
port = 5000
ident = "lttpoll.com"
log_level = "normal"
limits = { forms = 4096 }

[default.databases.lttpoll]
url = "postgresql://lttpoll:MFC1IaNHPlCrlKZQ2VZl27p6OhK24v7t4EgBJ9Ya15lNkCG2@localhost:54320/lttpoll"
pool_size = 10
timeout = 10
tls = { accept_invalid_certs = false, accept_invalid_hostnames = false }
#tls = { accept_invalid_certs = false, accept_invalid_hostnames = false, cert_path = "" }

[release]
log_level = "critical"
